[package]
name = "AdventOfCode2019InRust"
version = "0.1.0"
authors = ["Max Doerner <maxdoerner@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
